import "../globals.css";
import type { Metadata } from "next";
import ResponsiveDrawer from "@/components/ui/navigation/Sidebar";

export const metadata: Metadata = {
  title: "Sistema Inventarios de TI UNFV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <ResponsiveDrawer>{children}</ResponsiveDrawer>;
}
