import ThemeRegistry from "@/utils/mui-config/ThemeRegistry";
import "./globals.css";
import type { Metadata } from "next";
import SessionAuthProvider from "@/auth/context/SessionAuthProvider";
import { Session } from "next-auth";
import { headers } from 'next/headers'


async function getMySession(cookie: string): Promise<Session> {
  const response = await fetch(`${process.env.NEXTAUTH_URL}/api/auth/session`, {
    headers: {
      "Content-Type": "application/json",
      cookie,
    }
  })

  const session = await response.json()

  return Object.keys(session).length > 0 ? session : null
}

export const metadata: Metadata = {
  title: "Sistema Inventarios de TI UNFV",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session =  await getMySession(headers().get('cookie') ?? '');

  return (
    <html lang="en">
      <body>
        <SessionAuthProvider session={session}>
          <ThemeRegistry>{children}</ThemeRegistry>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
