import ThemeRegistry from "@/utils/mui-config/ThemeRegistry";
import "./globals.css";
import type { Metadata } from "next";
import SessionAuthProvider from "@/auth/context/SessionAuthProvider";

export const metadata: Metadata = {
  title: "Sistema Inventarios de TI UNFV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionAuthProvider>
          <ThemeRegistry>{children}</ThemeRegistry>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
